title: felicity.love
description: A daily devotional website for practicing the christian faith inspired by my friend Felicity whom I love dearly.


remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

base-url: felicity.love

# defaults:
#   - scope:
#       path: "/"
#     values:
#       layout: default
#   - scope:
#       path: "_posts"
#     values:
#       layout: post

permalink: /:year/:month/:day/:title/